import Head from "next/head";
import s from "assets/styles/home.module.scss";
import Section from "components/section";
import Footer from "components/footer";
import { ReactNode } from "react";
import Header from "components/header";

interface layoutProp {
  children: React.ReactNode;
  footer: boolean | ReactNode;
  header: boolean | ReactNode;
}
function Layout({ children, footer, header }: layoutProp) {
  return (
    <div className={s.body}>
      <Head>
        <title>Explore App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.container}>
        {typeof header == "boolean" ? header && <Header /> : header}
        {children}
        {typeof footer == "boolean" ? footer && <Footer /> : footer}
      </div>
    </div>
  );
}
export default function Home() {
  return (
    <Layout footer={<Footer />} header={<Header />}>
      <Section />
    </Layout>
  );
}
