import Head from "next/head";
import s from "assets/styles/home.module.scss";
import { Layout } from "components";
import gate from "components/gate";
import { useEffect, useState } from "react";
import { ResponseGetProjectsDataType } from "components/gate/inerface/projects.interface";



export default function Home() {

  return (
    <div className={s.body}>
      <Head>
        <title>Explore App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </div>
  );
}
