import Head from "next/head";
import s from "assets/styles/home.module.scss";
import {Footer }from "components/explore";
import { ReactNode } from "react";
import {Header} from "components/explore";

interface layoutProp {
  children: React.ReactNode;
  footer: boolean | ReactNode;
  header: boolean | ReactNode;
}
export function Layout({ children, footer, header }: layoutProp) {
  return (
    <div className={s.body}>
      <Head>
        <title>Explore App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.container}>
        {typeof header == "boolean" ? header && <Header /> : header}
        {children}
        {typeof footer == "boolean" ? footer && <Footer /> : footer}
      </div>
    </div>
  );
}
